# Generated by Django 4.0.3 on 2022-03-09 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suratmasuk', '0002_alter_suratmasuk_tgl_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratmasuk',
            name='tgl_masuk',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
