# Generated by Django 4.0.3 on 2022-03-09 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_surat', models.CharField(max_length=50)),
                ('kode_surat', models.CharField(max_length=50)),
                ('tgl_keluar', models.DateField(default=datetime.datetime(2022, 3, 9, 16, 36, 9, 517591))),
                ('ditujukan', models.CharField(max_length=100)),
                ('perihal', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=200)),
                ('kategori', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=10)),
                ('lampiran', models.CharField(max_length=100)),
                ('sifat', models.CharField(max_length=100)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
