# Generated by Django 4.0.3 on 2022-03-09 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suratkeluar', '0002_alter_suratkeluar_tgl_keluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkeluar',
            name='tgl_keluar',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
