# Generated by Django 4.0.3 on 2022-03-09 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suratmasuk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_surat', models.CharField(max_length=10)),
                ('diteruskan', models.CharField(max_length=100)),
                ('dari', models.CharField(max_length=100)),
                ('dgn_hormat', models.CharField(max_length=100)),
                ('tgl_surat', models.DateField(default=datetime.datetime(2022, 3, 9, 16, 36, 9, 515522))),
                ('tgl_diterima', models.DateField(default=datetime.datetime(2022, 3, 9, 16, 36, 9, 515553))),
                ('sifat', models.CharField(max_length=100)),
                ('perihal', models.TextField()),
                ('catatan', models.TextField()),
                ('v_read', models.IntegerField()),
                ('tanggapan', models.TextField()),
                ('tujuan', models.TextField()),
                ('teruntuk', models.CharField(max_length=150)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('smasuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suratmasuk.suratmasuk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
