# Generated by Django 4.0.3 on 2022-03-09 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='tgl_diterima',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 16, 37, 59, 765639)),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='tgl_surat',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 16, 37, 59, 765611)),
        ),
    ]
