# Generated by Django 4.0.3 on 2022-03-09 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0002_alter_disposisi_tgl_diterima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='tgl_diterima',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='tgl_surat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
