# Generated by Django 4.0.3 on 2022-03-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
        ('disposisi', '0003_alter_disposisi_tgl_diterima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai'),
        ),
    ]
