# Generated by Django 4.0.3 on 2022-03-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nip',
        ),
    ]
