# Generated by Django 4.0.3 on 2022-03-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0002_remove_users_name_remove_users_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='profile/undraw_profile.svg', upload_to=''),
        ),
    ]
